// RootLayout.js

import React from 'react';
import { Inter } from 'next/font/google';
import Head from 'next/head'; // Import Head from Next.js for managing metadata
import Navbar from './Navbar/Navbar'; // Import your Navbar component
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }) => {
  return (
    <>
      <Head>
        {/* Define metadata for the page */}
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        {/* Add any other meta tags, stylesheets, or scripts here */}
      </Head>
      <html lang="en">
        <body className={inter.className}>
          <Navbar /> {/* Render the Navbar component here */}
          
          {children}
          
        </body>
      </html>
    </>
  );
};

export default RootLayout;
